backend:
  name: github
  repo: lawyeraymankhalil/LawyerAymankhalilal-ali
  branch: main
  base_url: https://ayman-cms-auth.ayminkhalil2003.workers.dev
  auth_endpoint: auth

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "articles"
    label: "المقالات"
    label_singular: "مقال"
    files:
      - name: "articles_list"
        label: "قائمة المقالات"
        file: "data/articles.json"
        fields:
          - {label: "المقالات", name: "articles", widget: "list", fields:
              - {label: "التصنيف", name: "tag", widget: "string"}
              - {label: "العنوان", name: "title", widget: "string"}
              - {label: "النص", name: "body", widget: "text"}
              - {label: "التاريخ", name: "date", widget: "string"}
              - {label: "مدة القراءة", name: "read", widget: "string"}
            }
